### ISSUE TITLE
Bundle not showing as a running applicication

### ISSUE THREAD

**Issue by Rharris11** [liftsecurity/BurpSuite-MacOS#3]
Good afternoon

I just created my Burp install using your build scripts and everything seemed fine.  I launch that application from the Application folder and it runs but for some reason it is not showing as a running application on that mac.  I do not have any of the menu options so I can't fully utilize the tool.  Do you have any recommendation as to what could be the cause of this?  Thanks in advance for your help.

**Comment by jlamendo** [comment]
@Rharris11 Burp is still a java application, no matter what wrapper I placed around it. Unfortunately that means it will never be able to use the native macos gui, unless Apple decides to allow it, or Burp is ported to a native language( unlikely ). You should still see the burpsuite menus along the top of the application window though - if the case is that you aren't seeing those menus, there's something wrong.

**Comment by jlamendo** [comment]
Over a year old with no further information, closing for now.
